import { z } from 'zod';
import type {
  CostCode,
  ActualCostRecord,
  BaselineBudgetRecord,
  CostPhasingRecord,
  EtcDetail,
  PeriodSnapshot,
} from '../types';

export const CostCodeSchema = z.object({
  id: z.string(),
  code: z.string(),
  projectId: z.string(),
  name: z.string(),
  enterpriseAttributes: z.record(z.string(), z.string()),
  projectAttributes: z.record(z.string(), z.string()),
  eacMethod: z.enum(['Manual', 'Change Management', 'ETC Details', 'Sub-Contract Management']),
  sortOrder: z.number(),
  activityId: z.string().optional(),
  plannedStartDate: z.string().optional(),
  plannedEndDate: z.string().optional(),
  baselineBudget: z.number(),
  budgetChanges: z.number(),
  approvedBudget: z.number(),
  approvedBudgetPrevious: z.number(),
  approvedBudgetMovement: z.number(),
  actualCostThisPeriod: z.number(),
  actualCostToDate: z.number(),
  estimateToComplete: z.number(),
  estimateAtCompletion: z.number(),
  estimateAtCompletionPrevious: z.number(),
  estimateAtCompletionMovement: z.number(),
  costVariance: z.number(),
  costVariancePrevious: z.number(),
  costVarianceMovement: z.number(),
  assignedUsers: z.array(z.string()).optional(),
});

export const ActualCostRecordSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  costCodeId: z.string(),
  item: z.string(),
  description: z.string(),
  source: z.enum(['MAN', 'ACC', 'FIN', 'REV']),
  cost: z.number(),
  reportingPeriodId: z.string(),
  enterpriseAttributes: z.record(z.string(), z.string()).optional(),
  projectAttributes: z.record(z.string(), z.string()).optional(),
  createdAt: z.string(),
  updatedAt: z.string().optional(),
});

export const BaselineBudgetRecordSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  costCodeId: z.string(),
  item: z.string(),
  description: z.string(),
  source: z.enum(['EST', 'CON', 'BID']),
  amount: z.number(),
  reportingPeriodId: z.string(),
  enterpriseAttributes: z.record(z.string(), z.string()).optional(),
  projectAttributes: z.record(z.string(), z.string()).optional(),
  createdAt: z.string(),
  updatedAt: z.string().optional(),
});

export const CostPhasingRecordSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  costCodeId: z.string(),
  periodValues: z.record(z.string(), z.number()),
  type: z.string(),
  createdAt: z.string(),
  updatedAt: z.string().optional(),
});

export const EtcDetailSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  costCode: z.string(),
  calendarId: z.string().optional(),
  category: z.string().optional(),
  item: z.string(),
  description: z.string(),
  orderNumber: z.string(),
  udf1: z.string(),
  udf2: z.string(),
  udf3: z.string(),
  udf4: z.string(),
  qty: z.number(),
  unit: z.string(),
  rate: z.number(),
  phasingMethod: z.enum(['Manual', 'Auto-Phase']),
  phasingStartDate: z.string(),
  phasingEndDate: z.string(),
  activityId: z.string().optional(),
  phasingUnit: z.enum(['Daily', 'Weekly', 'Monthly', 'Total', 'Profile']),
  phasingQty: z.number(),
  enterpriseAttributes: z.record(z.string(), z.string()).optional(),
  projectAttributes: z.record(z.string(), z.string()).optional(),
  periodValues: z.record(z.string(), z.number()),
  sortOrder: z.number(),
  createdAt: z.string(),
  updatedAt: z.string().optional(),
  isEnterpriseResource: z.boolean().optional(),
  resourceId: z.string().optional(),
  totalEtcPrevious: z.number().optional(),
});

const PeriodSnapshotCostCodeEntrySchema = z.object({
  costCodeId: z.string(),
  costCode: z.string(),
  name: z.string(),
  approvedBudget: z.number(),
  actualCostToDate: z.number(),
  estimateToComplete: z.number(),
  estimateAtCompletion: z.number(),
  costVariance: z.number(),
});

export const PeriodSnapshotSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  periodId: z.string(),
  periodName: z.string(),
  costCodes: z.array(PeriodSnapshotCostCodeEntrySchema),
  createdAt: z.string(),
});
