import { z } from 'zod';
import type { Subcontract, SubcontractLineItem, Invoice, InvoiceItem } from '../types';

const DistributionCurveSchema = z.enum([
  'Even',
  'Bell Curve',
  'Front load',
  'Back load',
  'S-Curve',
  'Profile',
]);

export const SubcontractLineItemSchema = z.object({
  id: z.string(),
  subcontractId: z.string(),
  projectId: z.string(),
  itemNo: z.string(),
  description: z.string(),
  activityId: z.string().optional(),
  costCodeId: z.string().optional(),
  date: z.string().optional(),
  qty: z.number(),
  unit: z.string(),
  rate: z.number(),
  total: z.number(),
  type: z.enum(['Original', 'ChangeOrder']),
  status: z.enum(['Approved', 'Pending', 'Forecast', 'Rejected']),
  startDate: z.string().optional(),
  endDate: z.string().optional(),
  phasingSource: z.enum(['Manual', 'Auto']).optional(),
  distribution: DistributionCurveSchema.optional(),
  periodValues: z.record(z.string(), z.number()).optional(),
  enterpriseAttributes: z.record(z.string(), z.string()),
  projectAttributes: z.record(z.string(), z.string()),
  userDefined: z.record(z.string(), z.any()).optional(),
  note: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export const SubcontractSchema = z.object({
  id: z.string(),
  projectId: z.string(),
  enterpriseId: z.string(),
  orderId: z.string(),
  orderName: z.string(),
  orderScope: z.string(),
  status: z.enum(['Active', 'Complete', 'On Hold']),
  defaultCostCodeId: z.string().optional(),
  defaultPhasingSource: z.enum(['Manual', 'Auto']).optional(),
  defaultStartDate: z.string().optional(),
  defaultEndDate: z.string().optional(),
  defaultDistribution: DistributionCurveSchema.optional(),
  paymentType: z.enum(['LumpSum', 'Schedule of Rates', 'Re-measurable']),
  awardDate: z.string(),
  vendorId: z.string(),
  vendorName: z.string(),
  vendorUsers: z.array(z.string()),
  totalAmount: z.number(),
  forecastChanges: z.number().optional(),
  lineItems: z.array(SubcontractLineItemSchema),
  enterpriseSubcontractAttributes: z.record(z.string(), z.string()).optional(),
  projectAttributes: z.record(z.string(), z.string()).optional(),
  attributes: z.record(z.string(), z.any()).optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
  createdBy: z.string().optional(),
});

export const InvoiceItemSchema = z.object({
  id: z.string(),
  subcontractLineItemId: z.string(),
  itemNo: z.string(),
  description: z.string(),
  qty: z.number(),
  unit: z.string(),
  rate: z.number(),
  total: z.number(),
  type: z.enum(['Original', 'ChangeOrder']).optional(),
  claimQty: z.number(),
  claimPercent: z.number(),
  claimValue: z.number(),
  periodicClaimQty: z.number().optional(),
  periodicClaimPercent: z.number().optional(),
  periodicClaimValue: z.number().optional(),
  certifiedQty: z.number(),
  certifiedPercent: z.number(),
  certifiedValue: z.number(),
  periodicCertifiedQty: z.number().optional(),
  periodicCertifiedPercent: z.number().optional(),
  periodicCertifiedValue: z.number().optional(),
  commentary: z.string().optional(),
});

export const InvoiceSchema = z.object({
  id: z.string(),
  subcontractId: z.string(),
  projectId: z.string(),
  enterpriseId: z.string(),
  invoiceId: z.string(),
  description: z.string(),
  submittedDate: z.string().optional(),
  certifiedDate: z.string().optional(),
  paymentDate: z.string().optional(),
  status: z.enum(['Draft', 'Submitted', 'Certified', 'Rejected', 'Paid']),
  initiator: z.string().optional(),
  vendorId: z.string(),
  vendorName: z.string(),
  totalAmount: z.number(),
  certifiedAmount: z.number(),
  items: z.array(InvoiceItemSchema),
  createdAt: z.string(),
  updatedAt: z.string(),
  createdBy: z.string().optional(),
});
